# TCL File Generated by Component Editor 18.1
# Mon Mar 24 21:22:04 CET 2025
# DO NOT MODIFY


# 
# soc_performance_analyzer "soc_performance_analyzer" v1.0
#  2025.03.24.21:22:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module soc_performance_analyzer
# 
set_module_property DESCRIPTION ""
set_module_property NAME soc_performance_analyzer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME soc_performance_analyzer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL soc_performance_analyzer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file soc_performance_analyzer_module.vhd VHDL PATH soc_performance_analyzer_module/soc_performance_analyzer_module.vhd


# 
# parameters
# 
add_parameter RAM_ADDRESS_WIDTH_B_IN INTEGER 10 ""
set_parameter_property RAM_ADDRESS_WIDTH_B_IN DEFAULT_VALUE 10
set_parameter_property RAM_ADDRESS_WIDTH_B_IN DISPLAY_NAME RAM_ADDRESS_WIDTH_B_IN
set_parameter_property RAM_ADDRESS_WIDTH_B_IN TYPE INTEGER
set_parameter_property RAM_ADDRESS_WIDTH_B_IN UNITS None
set_parameter_property RAM_ADDRESS_WIDTH_B_IN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RAM_ADDRESS_WIDTH_B_IN DESCRIPTION ""
set_parameter_property RAM_ADDRESS_WIDTH_B_IN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point write_port
# 
add_interface write_port avalon end
set_interface_property write_port addressUnits WORDS
set_interface_property write_port associatedClock clock
set_interface_property write_port associatedReset reset
set_interface_property write_port bitsPerSymbol 8
set_interface_property write_port burstOnBurstBoundariesOnly false
set_interface_property write_port burstcountUnits WORDS
set_interface_property write_port explicitAddressSpan 0
set_interface_property write_port holdTime 0
set_interface_property write_port linewrapBursts false
set_interface_property write_port maximumPendingReadTransactions 0
set_interface_property write_port maximumPendingWriteTransactions 0
set_interface_property write_port readLatency 0
set_interface_property write_port readWaitTime 1
set_interface_property write_port setupTime 0
set_interface_property write_port timingUnits Cycles
set_interface_property write_port writeWaitTime 0
set_interface_property write_port ENABLED true
set_interface_property write_port EXPORT_OF ""
set_interface_property write_port PORT_NAME_MAP ""
set_interface_property write_port CMSIS_SVD_VARIABLES ""
set_interface_property write_port SVD_ADDRESS_GROUP ""

add_interface_port write_port write_data writedata Input 32
add_interface_port write_port write write Input 1
set_interface_assignment write_port embeddedsw.configuration.isFlash 0
set_interface_assignment write_port embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment write_port embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment write_port embeddedsw.configuration.isPrintableDevice 0


# 
# connection point read_port
# 
add_interface read_port avalon end
set_interface_property read_port addressUnits WORDS
set_interface_property read_port associatedClock clock
set_interface_property read_port associatedReset reset
set_interface_property read_port bitsPerSymbol 8
set_interface_property read_port burstOnBurstBoundariesOnly false
set_interface_property read_port burstcountUnits WORDS
set_interface_property read_port explicitAddressSpan 0
set_interface_property read_port holdTime 0
set_interface_property read_port linewrapBursts false
set_interface_property read_port maximumPendingReadTransactions 0
set_interface_property read_port maximumPendingWriteTransactions 0
set_interface_property read_port readLatency 0
set_interface_property read_port readWaitStates 3
set_interface_property read_port readWaitTime 3
set_interface_property read_port setupTime 0
set_interface_property read_port timingUnits Cycles
set_interface_property read_port writeWaitTime 0
set_interface_property read_port ENABLED true
set_interface_property read_port EXPORT_OF ""
set_interface_property read_port PORT_NAME_MAP ""
set_interface_property read_port CMSIS_SVD_VARIABLES ""
set_interface_property read_port SVD_ADDRESS_GROUP ""

add_interface_port read_port read_address address Input "(ram_address_width_b_in) - (0) + 1"
add_interface_port read_port read_data readdata Output 32
add_interface_port read_port read read Input 1
set_interface_assignment read_port embeddedsw.configuration.isFlash 0
set_interface_assignment read_port embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment read_port embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment read_port embeddedsw.configuration.isPrintableDevice 0

