// system_id.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module system_id (
		input  wire        clkin,      //  clkin.clk
		input  wire        reset,      //  reset.reset
		output wire        data_valid, // output.valid
		output wire [63:0] chip_id     //       .data
	);

	altchip_id #(
		.DEVICE_FAMILY ("Cyclone V"),
		.ID_VALUE      (64'b1111111111111111111111111111111111111111111111111111111111111111)
	) system_id_inst (
		.clkin      (clkin),      //  clkin.clk
		.reset      (reset),      //  reset.reset
		.data_valid (data_valid), // output.valid
		.chip_id    (chip_id)     //       .data
	);

endmodule
